AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ExecBot:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../dist/backend
      Handler: index.execBot
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          S3_BUCKET: !Ref BucketName
          SLACK_BOT_TOKEN: !Ref SlackBotToken
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /slack_events
            Method: post

Parameters:
  SlackBotToken:
    Type: String
  BucketName:
    Type: String
